//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.Track = new HashSet<Track>();
        }
    
        public int id_album { get; set; }
        public string name_album { get; set; }
        public int id_performer { get; set; }
        public int id_genre { get; set; }
        public string label { get; set; }
        public System.DateTime date_release { get; set; }
        public int count_track { get; set; }
        public string links { get; set; }
        public string Img { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Performer Performer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Track> Track { get; set; }
    }
}
