//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int id_track { get; set; }
        public string name_track { get; set; }
        public System.TimeSpan duration { get; set; }
        public int id_album { get; set; }
    
        public virtual Album Album { get; set; }
    }
}
